FROM ubuntu:18.04
RUN mkdir /opt/nvidia
COPY ./nvidia /opt/nvidia
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install zlib1g
RUN apt-get install -y python3.6
RUN apt-get install -y python3-pip
